---
- name: Ensure kalite is stopped if service exist
  service: name=kalite state=stopped
  ignore_errors: yes
  tags: ['configure']

- name: Create a working dir Kalite
  file: path=/home/{{ username }}/.kalite state=directory
  tags: ['configure']

  # Otherwise Ka-lite install Django2 to fullfill Django>=1.5 requirements
  # which is not available on python2.
- name: Install Django 1.11.8 for Ka-lite
  pip: name=Django
    version=1.11.8
    chdir=/home/{{ username }}/.kalite
    virtualenv_command=/usr/bin/virtualenv
    virtualenv=/home/{{ username }}/.kalite/env
  tags: ['configure']

- name: Install Ka-lite
  pip: name=ka-lite
    version={{ kalite_version }}
    chdir=/home/{{ username }}/.kalite
    virtualenv_command=/usr/bin/virtualenv
    virtualenv=/home/{{ username }}/.kalite/env
  register: kalite_installation 
  tags: ['configure']

- name: Give rights to ideascube 
  file:
    path: /home/{{ username }}/.kalite
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes
    state: directory
  tags: ['configure']

- name: Create a user admin for kalite
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage setup --username=admin --password=admin --noinput
  tags: ['configure']

- name: Copy nginx vhost
  template: src=kalite.vhost.j2 dest=/etc/nginx/sites-available/kalite
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Nginx enable Virtual host
  file: src=/etc/nginx/sites-available/kalite dest=/etc/nginx/sites-enabled/kalite state=link
  notify: restart nginx
  tags: [configure']

- name: Setup startup file
  copy: src=kalite.service dest=/etc/systemd/system/kalite.service
  tags: ['configure']

- name: Enable service kalite
  service: name=kalite enabled=yes
  tags: ['configure']

- name: Generate a zone for kalite
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage generate_zone
  ignore_errors: yes
  tags: ['configure']

- name: Run kalite manage setup after upgrade
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage setup --noinput
  when: kalite_installation.changed == True
  tags: ['configure']

- name: Download Kalite language pack
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage retrievecontentpack download {{ item }}
  with_items: "{{ kalite_languages | default(omit) }}"
  when: kalite_installation.changed == True
  tags: ['download-content']

- name: Start Kalite
  service: name=kalite state=started
  tags: ['configure']

- name: Restart Kalite
  service: name=kalite state=restarted
  when: kalite_installation.changed == True
  tags: [configure', 'download-content', 'move-content']

- name: Perfom a video scan on the device
  become: yes
  become_user: ideascube
  command: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py manage videoscan
  async: 1800
  poll: 0
  when: kalite_installation.changed == True
  tags: ['download-content', 'move-content']

- name: Get ka-lite version
  shell: /home/ideascube/.kalite/env/bin/python2 /home/ideascube/.kalite/env/share/kalite/kalitectl.py --version ; echo
  register: kalite_newversion
  tags: ['configure']

- set_fact: kalite_version="{{ kalite_newversion.stdout }}"
  tags: [configure']

- debug: msg="kalite {{ kalite_version }} is now the current version."
  tags: ['configure']

- include: post_install.yml task=kalite task_version="{{ kalite_version }}"
  tags: ['configure']  
