---
- name: Install nginx web server
  apt:
    name: nginx
    state: latest
    force: yes
    autoremove: yes
    autoclean: yes
  tags: master

- name: install 502.html
  template:
    src: 502.html.j2
    dest: /var/www/502.html
  tags: ['master', 'rename']

- name: install 404.html
  template:
    src: 404.html.j2
    dest: /var/www/404.html
  tags: ['master', 'rename']

- name: Remove default nginx vhost config file (if configured).
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx
  tags: master

- name: Upload nginx.conf
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    backup: yes
  notify: restart nginx
  tags: master

- name: install default placeholder vhost for services
  template:
    src: placeholder.j2
    dest: /etc/nginx/sites-enabled/{{ item.name }}
  with_items:
    - { name: 'edupi', fqdn: "{{ edupi_fqdn }}" }
    - { name: 'kalite', fqdn: "{{ kalite_fqdn }}" }
    - { name: 'aflatoun', fqdn: "{{ aflatoun_fqdn }}" }
    - { name: 'fr.wikifundi', fqdn: "fr.{{ wikifundi_fqdn }}" }
    - { name: 'en.wikifundi', fqdn: "en.{{ wikifundi_fqdn }}" }
  tags: master
