---
- name: create tar of {{ data_path }}
  become: yes
  become_user: "{{ username }}"
  args:
    chdir: "{{ data_path }}"
  shell: tar --dereference --hard-dereference -cf /home/{{ username }}/data_part.tar *
  tags: reconfigure
