---
- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: latest
    autoremove: yes
  with_items:
    - nginx
    - libmagickwand-dev
    - virtualenv
    - npm
    - nodejs
  tags: configure

- name: Link node to nodejs binary
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  tags: configure

- name: Install bower
  npm:
    name: bower
    global: yes
    state: latest
  tags: configure

- name: Create directories
  become: yes
  become_user: ideascube
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ edupi_root }}/"
    - "{{ edupi_root }}/database"
    - "{{ edupi_root }}/static"
    - "{{ edupi_root }}/media"
    - "{{ edupi_root }}/stats"
  tags: configure

- name: remove edupi folder if it exists
  become: yes
  become_user: ideascube
  file:
    dest: "{{ edupi_root }}/edupi"
    state: absent
  tags: configure

- name: remove edupi env if it exists
  become: yes
  become_user: ideascube
  file:
    dest: "{{ edupi_env }}"
    state: absent
  tags: configure

- name: Download edupi
  become: yes
  become_user: ideascube
  git:
    repo: https://github.com/rgaudin/edupi.git
    dest: "{{ edupi_root }}/edupi/"
    version: v{{ edupi_version }}
  tags: configure

- name: Replace allowed hosts
  become: yes
  become_user: ideascube
  replace:
    name: "{{ edupi_root }}/edupi/edupi/settings.py"
    regexp: '^ALLOWED_HOSTS = \[''edupi.fondationorange.org''\]$'
    replace: 'ALLOWED_HOSTS = [''.{{ fqdn }}'', ''{{ fqdn }}'', ''{{ hostname }}'', ''localhost'']'
  notify: restart edupi
  tags: ['configure', 'rename']

- name: Create python{{ python3_version }} environment
  become: yes
  become_user: ideascube
  command: virtualenv --python=python{{ python3_version }} {{ edupi_env }}
  tags: configure

- name: Install requirements
  become: yes
  become_user: ideascube
  pip:
    requirements: "{{ edupi_root }}/edupi/requirements.txt"
    executable: "{{ edupi_env }}/bin/pip"
  tags: configure

- name: Manage install bower
  become: yes
  become_user: ideascube
  command: "{{ edupi_env }}/bin/python3 {{ edupi_root }}/edupi/manage.py bower install"
  tags: configure

- name: Manage migrate
  become: yes
  become_user: ideascube
  command: "{{ edupi_env }}/bin/python3 {{ edupi_root }}/edupi/manage.py migrate"
  tags: configure

- name: Check if EduPi super user is installed
  become: yes
  become_user: ideascube
  command: /bin/echo "from django.contrib.auth.models import User; print('****{}****'.format(User.objects.filter(username='{{ admin_account }}').count()))" | {{ edupi_env }}/bin/python3 {{ edupi_root }}/edupi/manage.py shell --plain
  register: edupi_admin_shell_output
  when: admin_account is defined
  tags: configure

- name: Install EduPi super user
  become: yes
  become_user: ideascube
  command: /bin/echo "from django.contrib.auth.models import User; User.objects.create_superuser('{{ admin_account }}', None, '{{ admin_password }}')" | {{ edupi_env }}/bin/python3 {{ edupi_root }}/edupi/manage.py shell --plain
  when: admin_account is defined and edupi_admin_shell_output.stdout.split('****')[1]|int == 0
  tags: configure

- name: Manage collectstatic
  become: yes
  become_user: ideascube
  command: "{{ edupi_env }}/bin/python3 {{ edupi_root }}/edupi/manage.py collectstatic --noinput"
  tags: configure

- name: Copy nginx vhost
  template:
    src: edupi.vhost.j2
    dest: /etc/nginx/sites-available/edupi
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Nginx enable Virtual host
  file:
    src: /etc/nginx/sites-available/edupi
    dest: /etc/nginx/sites-enabled/edupi
    state: link
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Setup edupi service
  template:
    src: edupi.service.j2
    dest: /etc/systemd/system/edupi.service
  tags: configure

- name: Enable and Start Edupi
  systemd:
    name: edupi
    state: started
    daemon_reload: yes
    enabled: yes
  tags: configure

- include: mark_role.yml role=edupi_setup
  tags: configure
