before_install:
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv -in travis_secrets.tar.enc -out travis_secrets.tar -d
- tar xvf travis_secrets.tar
- chmod 600 pibox_installer_ci_rsa

addons:
  ssh_known_hosts:
  - download.kiwix.org

matrix:
  include:
  - language: python
    python:
      - "2.7"
    sudo: false
    install:
    - pip install -r ansiblecube/tests/requirements-dev.txt
    script:
    - cd ansiblecube
    - py.test

  - os: osx
    language: generic
    env:
      - PYTHON=3.6.4
      - CONFIGURE_OPTS="--enable-shared"
    install:
    # Package pibox-installer
    - brew update
    - brew install openssl readline
#    - brew install pygobject3 --with-python3 gtk+3 adwaita-icon-theme
    - brew outdated pyenv || brew upgrade pyenv
    - pyenv install $PYTHON
    - export PYENV_VERSION=$PYTHON
    - export PATH="/Users/travis/.pyenv/shims:${PATH}"
    - pyenv global $PYTHON
    - python --version
    - python -m pip install -U pip setuptools
    - python3 --version
    - python3 -m pip install pygobject
    - python3 -m pip install -r requirements-macos.txt
    - python3 -m pip install https://github.com/pyinstaller/pyinstaller/archive/93eec04eb2fbfc714d2c3453e04fd126e6a86f52.zip

    # Download pibox-installer-vexpress-boot
    - wget http://download.kiwix.org/dev/pibox-installer-vexpress-boot.zip
    - unzip pibox-installer-vexpress-boot.zip

    # Bundle QEMU
    - wget http://download.kiwix.org/dev/qemu-2.12.0_macOS.tar
    - tar xf qemu-2.12.0_macOS.tar

    # Run PyInstaller
    - /Users/travis/.pyenv/versions/$PYTHON/bin/pyinstaller --log-level=DEBUG pibox-installer-macos.spec

    # Sign application
    - security create-keychain -p mysecretpassword build.keychain
    - security default-keychain -s build.keychain
    - security unlock-keychain -p mysecretpassword build.keychain
    - security import pibox-installer.p12 -k build.keychain -P $MACOS_CERTIFICATE_PASSWORD -A
    - "security set-key-partition-list -S apple-tool:,apple: -s -k mysecretpassword build.keychain"
    - security find-identity -v
    - "codesign -s \"Developer ID Application: Wikimedia CH (L7HWM3SP3L)\" dist/kiwix-plug_installer.app --deep"

    # Install and run create-dmg
    - npm install --global create-dmg@2.0.0 --python=python2.7
    - create-dmg dist/kiwix-plug_installer.app || true
    - mv kiwix-plug_installer-0.0.0.dmg kiwix-plug_installer-macos.dmg

    # Send dmg
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa kiwix-plug_installer-macos.dmg nightlybot@download.kiwix.org:/var/www/download.kiwix.org/nightly/$(date +"%Y-%m-%d")/kiwix-plug_installer-macos-$BRANCH.dmg

    - PIBOX_RELEASE=$(echo $TRAVIS_TAG | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*\(-rc[[:digit:]]\+\)\?') || true
    - if [ $PIBOX_RELEASE ]; then mkdir -p releases/$PIBOX_RELEASE; cp kiwix-plug_installer-macos.dmg releases/$PIBOX_RELEASE/; scp -r -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa releases/$PIBOX_RELEASE nightlybot@download.kiwix.org:/var/www/download.kiwix.org/release/kiwix-plug_installer/; fi

  - os: linux
    language: python
    python: 3.4
    dist: trusty
    sudo: required
    virtualenv:
      system_site_packages: true
    addons:
      apt:
        packages:
          # Some package may not be required
          python3-gi
          python3-gi-cairo
          python3-cairo
          gir1.2-gtk-3.0
          libdbus-1-dev
          libdbus-glib-1-dev
          libffi-dev
          build-essential
          libssl-dev
          python-dev
          python3-dev
          libgdk-pixbuf2.0-dev
    script:
    # update XZ (trusty version -5.0.5 is too old)
    - wget http://download.kiwix.org/dev/xz-5.2.4.tar.gz
    - tar xf xz-5.2.4.tar.gz
    - cd xz-5.2.4
    - ./configure --enable-shared
    - make
    - sudo make install
    - sudo ldconfig
    - cd ..

    # Download pibox-installer-vexpress-boot
    - wget http://download.kiwix.org/dev/pibox-installer-vexpress-boot.zip
    - unzip pibox-installer-vexpress-boot.zip

    # get static QEMU
    - wget http://download.kiwix.org/dev/qemu-2.12.0-linux-x86_64.tar.gz
    - tar xf qemu-2.12.0-linux-x86_64.tar.gz

    # Install python dependancies
    - pip3 install -r requirements-linux.txt

    # Install and run pyinstaller
    # note: we temporary use a fork that resolves pygobject issues
    - pip3 install https://github.com/thiolliere/pyinstaller/archive/develop.zip
    - pyinstaller --log-level=DEBUG pibox-installer-linux.spec
    - cat build/pibox-installer-linux/warnpibox-installer-linux.txt

    # Archive
    - cd dist
    - tar czvf kiwix-plug_installer-linux.tar.gz kiwix-plug_installer
    - cd ..

    # Deploy
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa dist/kiwix-plug_installer-linux.tar.gz nightlybot@download.kiwix.org:/var/www/download.kiwix.org/nightly/$(date +"%Y-%m-%d")/kiwix-plug_installer-linux-$BRANCH.tar.gz

    - PIBOX_RELEASE=$(echo $TRAVIS_TAG | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*\(-rc[[:digit:]]\+\)\?') || true
    - if [ $PIBOX_RELEASE ]; then mkdir -p releases/$PIBOX_RELEASE; cp dist/kiwix-plug_installer-linux.tar.gz releases/$PIBOX_RELEASE; scp -r -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa releases/$PIBOX_RELEASE nightlybot@download.kiwix.org:/var/www/download.kiwix.org/release/kiwix-plug_installer/; fi
