before_install:
- openssl aes-256-cbc -K $encrypted_af8ee76d875e_key -iv $encrypted_af8ee76d875e_iv -in travis_secrets.tar.enc -out travis_secrets.tar -d
- tar xvf travis_secrets.tar
- chmod 600 pibox_installer_ci_rsa

addons:
  ssh_known_hosts:
  - download.kiwix.org
  - tmp.kiwix.org

matrix:
  include:
  - os: osx
    osx_image: xcode10.1
    language: generic
    python: 3.7.1  # just a label
    install:
    - ls -lha
    - echo $MACOS_CERTIFICATE_PASSWORD > .pwd
    - chmod 600 pibox-installer.p12 .pwd
    - scp -v -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa pibox-installer.p12 .pwd ci@tmp.kiwix.org:/home/reg/ci/
