version: 1.0.{build}

clone_folder: c:\projects\kiwix-hotspot

image: Visual Studio 2015

build: off

environment:
  kiwix_certificate_secret:
    secure: 5NoKiSa8D/4H1mZDpW/QvQ==

platform:
  - x64
  - x86

install:
  - set PATH=C:\Program Files (x86)\Windows Kits\10\bin\%platform%\;%PATH%

  # send all non-release build to tmp.kiwix.org except cron to nightly folder
  - ps: if ($env:APPVEYOR_SCHEDULED_BUILD -eq "true") { "/var/www/download.kiwix.org/nightly/" | Out-File C:\destination-ps.txt -NoNewline -Encoding ASCII; Get-Date -UFormat "%Y-%m-%d" | Out-File C:\destination-ps.txt -Append -NoNewline -Encoding ASCII } else  { "/var/www/tmp.kiwix.org/ci" | Out-File C:\destination-ps.txt -NoNewline -Encoding ASCII }

  # store branch name
  - if defined APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH (echo %APPVEYOR_PULL_REQUEST_HEAD_REPO_BRANCH% > branch.txt) else (echo %APPVEYOR_REPO_BRANCH% > branch.txt)
  - move branch.txt C:\msys64\home\appveyor\
  # store tag name
  - if defined APPVEYOR_REPO_TAG_NAME (echo %APPVEYOR_REPO_TAG_NAME% > C:\msys64\home\appveyor\tag.txt)
  # build-up version
  - ps: |
      $scommit = (git rev-parse --short $env:APPVEYOR_REPO_COMMIT) | Out-String
      $scommit = $scommit.Trim()
      If ($env:APPVEYOR_REPO_TAG_NAME) {
        $version = $env:APPVEYOR_REPO_TAG_NAME.Substring(1)
      } Elseif ($env:APPVEYOR_SCHEDULED_BUILD -eq "true") {
        $version="nightly (" + $scommit + ")"
      } Else {
        $version="CI (" + $scommit + ")"
      }
      (Get-Content pibox-installer\data.py).replace('devel', $version) | Set-Content pibox-installer\data.py

  # decrypt certificates
  - cmd: choco install openssl.light
  - openssl enc -d -aes-256-cbc -md sha256 -pass pass:%win_certificate_secret% -in kiwix.p12.enc -out kiwix.pfx
  - nuget install secure-file -ExcludeVersion
  - nuget install ResourceHacker.CommandLineTool -Version 4.7.34 
  - secure-file\tools\secure-file -decrypt pibox_installer_ci_rsa.appveyor_enc -secret %certificate_secret% -out pibox_installer_ci_rsa
  - ResourceHacker.CommandLineTool\tools\ResourceHacker.exe -help

  # Download vexpress-boot
  - appveyor DownloadFile "http://download.kiwix.org/dev/vexpress-boot.zip"
  - 7z.exe x vexpress-boot.zip

  # Install pygobject
  # pygi-aio provides a way to install from cmd even if it is not documented
  # the only package to install is GTK with GIR
  # note: we don't use msys2 because pyinstaller fails to install on msys2
  - appveyor DownloadFile "http://download.kiwix.org/dev/pygi-aio-3.18.2_rev12-setup_549872deadabb77a91efbc56c50fe15f969e5681.exe" -FileName "pygi-aio-setup.exe"
  - mkdir pygi-aio-setup
  - cd pygi-aio-setup
  - set SOURCEPATH=%cd%
  - 7z.exe x ..\pygi-aio-setup.exe
  - cd setup
  - del 7zr.exe
  - 7z.exe x ..\setup.exe
  - set GIR=True
  # note: we use python34 because it is the last supported by pygi-aio
  - if %platform%==x86 rcmd.exe /c setup.bat C:\Python34 GTK
  - if %platform%==x64 rcmd.exe /c setup.bat C:\Python34-x64 GTK
  # note: we create a symbolic link for pyinstaller
  - if %platform%==x86 mklink /D C:\Python34\share C:\Python34\Lib\site-packages\gnome\share
  - if %platform%==x64 mklink /D C:\Python34-x64\share C:\Python34-x64\Lib\site-packages\gnome\share
  - cd ..\..
  - if %platform%==x86 dir C:\Python34\Lib\site-packages\gi
  - if %platform%==x64 dir C:\Python34-x64\Lib\site-packages\gi

  # Install gdk-pixbuf and add it to PATH because it is needed by pyinstaller
  - if %platform%==x86 C:\msys64\usr\bin\bash --login -c "pacman -S mingw-w64-i686-gdk-pixbuf2 --noconfirm"
  - if %platform%==x86 set PATH=%PATH%;C:\msys64\mingw32\bin
  - if %platform%==x64 C:\msys64\usr\bin\bash --login -c "pacman -S mingw-w64-x86_64-gdk-pixbuf2 --noconfirm"
  - if %platform%==x64 set PATH=%PATH%;C:\msys64\mingw64\bin

  # Install pyinstaller and requirements
  - cd C:\projects\kiwix-hotspot
  - if %platform%==x86 C:\Python34\python.exe -m pip install pypiwin32==219 pyinstaller==3.2.1 -r requirements-windows.txt
  - if %platform%==x64 C:\Python34-x64\python.exe -m pip install pypiwin32==219 pyinstaller==3.2.1 -r requirements-windows.txt

  # Install qemu
  - mkdir "C:\Program Files\qemu"
  - cd "C:\Program Files\qemu"
  - if %platform%==x86 appveyor DownloadFile "http://download.kiwix.org/dev/qemu-w32-setup-20180430.exe" -FileName "qemu-setup.exe"
  - if %platform%==x64 appveyor DownloadFile "http://download.kiwix.org/dev/qemu-w64-setup-20180430.exe" -FileName "qemu-setup.exe"
  - 7z x qemu-setup.exe
  - del qemu-setup.exe
  - move qemu-system-arm.exe qemu-arm.exe
  - rmdir /S /Q keymaps lib share $PLUGINSDIR
  - del qemu-system-*
  - move qemu-arm.exe qemu-system-arm.exe
  - dir "C:\Program Files\qemu"

  # bundle 7zip
  - mkdir "C:\Program Files\7zextra"
  - cd "C:\Program Files\7zextra"
  - appveyor DownloadFile "http://download.kiwix.org/dev/7z920_extra.7z"
  - 7z.exe x 7z920_extra.7z
  - appveyor DownloadFile "http://download.kiwix.org/dev/7z1805-extra.7z"
  - 7z.exe -y x 7z1805-extra.7z

  # Copy Imdisk Installer
  - mkdir "C:\Program Files\imdiskinst"
  - cd "C:\Program Files\imdiskinst"
  - appveyor DownloadFile "http://download.kiwix.org/dev/imdiskinst.exe" -FileName "imdiskinst.exe"
  - 7z x imdiskinst.exe
  - del imdiskinst.exe
  - dir "C:\Program Files\imdiskinst"

  # Run pyinstaller and show warning
  - cd C:\projects\kiwix-hotspot
  - if %platform%==x86 C:\Python34\python.exe C:\Python34\Scripts\pyinstaller-script.py --log-level=DEBUG kiwix-hotspot-win32.spec
  - if %platform%==x64 C:\Python34-x64\python.exe C:\Python34-x64\Scripts\pyinstaller-script.py --log-level=DEBUG kiwix-hotspot-win64.spec
  - if %platform%==x86 type build\kiwix-hotspot-win32\warnkiwix-hotspot-win32.txt
  - if %platform%==x64 type build\kiwix-hotspot-win64\warnkiwix-hotspot-win64.txt

  # Deploy
  - cd C:\projects\kiwix-hotspot\dist\kiwix-hotspot
  - 7z.exe a -m0=Copy C:\projects\kiwix-hotspot\windows_bundle\kiwix-hotspot.7z *

  # download tools
  - cd C:\projects\kiwix-hotspot\windows_bundle\
  - appveyor DownloadFile "http://download.kiwix.org/dev/GoRC.exe" -FileName "GoRC.exe"
  # - appveyor DownloadFile "http://download.kiwix.org/dev/resource_hacker.zip" -FileName "resource_hacker.zip"
  # - 7z x resource_hacker.zip
  # create SFX exe from 7z archive
  - copy /b "C:\Program Files\7zextra\7zS.sfx" + sfxconfig.txt + kiwix-hotspot.7z kiwix-hotspot.exe
  # change icon and add version info to exe
  - GoRC.exe /fo resources.res resources.rc
  - copy ..\kiwix-hotspot-logo.ico icon.ico
  - ResourceHacker.exe -help
  - ResourceHacker.exe -script reshack.txt
  - c:\projects\kiwix-hotspot\ResourceHacker.CommandLineTool\tools\ResourceHacker.exe -script reshack.txt
  # - cd C:\projects\kiwix-hotspot\dist\kiwix-hotspot

  # sign the build
  # - signtool.exe sign /f C:\projects\kiwix-hotspot\kiwix.pfx /p %win_certificate_password% /t http://timestamp.verisign.com/scripts/timstamp.dll /d "Kiwix Hotspot" C:\projects\kiwix-hotspot\windows_bundle\kiwix-hotspot.exe

  - if %platform%==x86 move C:\projects\kiwix-hotspot\windows_bundle\kiwix-hotspot.exe C:\msys64\home\appveyor\kiwix-hotspot-win32.exe
  - if %platform%==x64 move C:\projects\kiwix-hotspot\windows_bundle\kiwix-hotspot.exe C:\msys64\home\appveyor\kiwix-hotspot-win64.exe
  - move C:\projects\kiwix-hotspot\pibox_installer_ci_rsa C:\msys64\home\appveyor\

  - if %platform%==x86 C:\msys64\usr\bin\bash --login -c "DESTINATION=$(cat /c/destination-ps.txt | tr -d '\r' | tr -d '\n') ; scp -r -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa kiwix-hotspot-win32.exe nightlybot@download.kiwix.org:$DESTINATION/kiwix-hotspot-win32-$(cat branch.txt | sed 's/ //g').exe"
  - if %platform%==x64 C:\msys64\usr\bin\bash --login -c "DESTINATION=$(cat /c/destination-ps.txt | tr -d '\r' | tr -d '\n') ; scp -r -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa kiwix-hotspot-win64.exe nightlybot@download.kiwix.org:$DESTINATION/kiwix-hotspot-win64-$(cat branch.txt | sed 's/ //g').exe"

  - C:\msys64\usr\bin\bash --login -c "PIBOX_RELEASE=$(cat tag.txt | sed 's/ //g' | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*\(-rc[[:digit:]]\+\)\?') || true; if [ $PIBOX_RELEASE ]; then mkdir -p releases/$PIBOX_RELEASE/; cp kiwix-hotspot-win*.exe releases/$PIBOX_RELEASE/; scp -r -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa releases/$PIBOX_RELEASE nightlybot@download.kiwix.org:/var/www/download.kiwix.org/release/kiwix-hotspot/; fi"
