version: 1.0.{build}

clone_folder: c:\projects\pibox-installer

image: Visual Studio 2015

build: off

platform:
  - x86
  - x64

environment:
  certificate_secret:
    secure: /Ephvg5HQQLR0IJmmeBGGpEww+93XqAMjdGAJKZyWsNeNCarAjvBDgcNBO/K1CWzwxpvty5sM0dZiWCFXt9kZcmU8vCPIYjwJE1B5Q5/mAQ=

install:
  # decrypt certificate
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt pibox_installer_ci_rsa.appveyor_enc -secret %certificate_secret% -out pibox_installer_ci_rsa

  # Download pibox-installer-vexpress-boot
  - appveyor DownloadFile "http://download.kiwix.org/dev/pibox-installer-vexpress-boot.zip"
  - 7z.exe x pibox-installer-vexpress-boot.zip

  # Download playbook
  - appveyor DownloadFile "https://github.com/thiolliere/ansiblecube/archive/oneUpdateFile0.3.zip"
  - 7z.exe x oneUpdateFile0.3.zip
  - move ansiblecube-oneUpdateFile0.3 ansiblecube

  # Install pygobject
  # pygi-aio provides a way to install from cmd even if it is not documented
  # the only package to install is GTK with GIR
  # note: we don't use msys2 because pyinstaller fails to install on msys2
  - appveyor DownloadFile "https://sourceforge.net/projects/pygobjectwin32/files/pygi-aio-3.18.2_rev12-setup_549872deadabb77a91efbc56c50fe15f969e5681.exe/download" -FileName "pygi-aio-setup.exe"
  - mkdir pygi-aio-setup
  - cd pygi-aio-setup
  - set SOURCEPATH=%cd%
  - 7z.exe x ..\pygi-aio-setup.exe
  - cd setup
  - del 7zr.exe
  - 7z.exe x ..\setup.exe
  - set GIR=True
  # note: we use python34 because it is the last supported by pygi-aio
  - rcmd.exe /c setup.bat C:\Python34 GTK
  # note: we create a symbolic link for pyinstaller
  - mklink /D C:\Python34\share C:\Python34\Lib\site-packages\gnome\share
  - cd ..\..
  - dir C:\Python34\Lib\site-packages\gi

  # Install gdk-pixbuf and add it to PATH because it is needed by pyinstaller
  - if %platform%==x86 C:\msys64\usr\bin\bash --login -c "pacman -S mingw-w64-i686-gdk-pixbuf2 --noconfirm"
  - if %platform%==x86 set PATH=%PATH%;C:\msys64\mingw32\bin
  - if %platform%==x64 C:\msys64\usr\bin\bash --login -c "pacman -S mingw-w64-x86_64-gdk-pixbuf2 --noconfirm"
  - if %platform%==x64 set PATH=%PATH%;C:\msys64\mingw64\bin

  # Install pyinstaller and requirements
  - cd C:\projects\pibox-installer
  - C:\Python34\python.exe -m pip install pyinstaller==3.2.1
  - C:\Python34\python.exe -m pip install -r requirements-windows.txt

  # Install qemu
  - mkdir "C:\Program Files\qemu"
  - cd "C:\Program Files\qemu"
  - if %platform%==x86 appveyor DownloadFile "https://qemu.weilnetz.de/w32/2017/qemu-w32-setup-20170420.exe" -FileName "qemu-setup.exe"
  - if %platform%==x64 appveyor DownloadFile "https://qemu.weilnetz.de/w64/2017/qemu-w64-setup-20170420.exe" -FileName "qemu-setup.exe"
  - 7z x qemu-setup.exe
  - dir "C:\Program Files\qemu"

  # Run pyinstaller and show warning
  - cd C:\projects\pibox-installer
  - if %platform%==x86 C:\Python34\python.exe C:\Python34\Scripts\pyinstaller-script.py --log-level=DEBUG pibox-installer-win32.spec
  - if %platform%==x64 C:\Python34\python.exe C:\Python34\Scripts\pyinstaller-script.py --log-level=DEBUG pibox-installer-win64.spec
  - if %platform%==x86 type build\pibox-installer-win32\warnpibox-installer-win32.txt
  - if %platform%==x64 type build\pibox-installer-win64\warnpibox-installer-win64.txt


  # Deploy
  - cd C:\projects\pibox-installer\dist\pibox-installer
  - 7z.exe a -m0=Copy C:\projects\pibox-installer\windows_bundle\pibox-installer.exe *

  - if %platform%==x86 move C:\projects\pibox-installer\windows_bundle\pibox-installer.exe C:\msys64\home\appveyor\pibox-installer-win32.exe
  - if %platform%==x64 move C:\projects\pibox-installer\windows_bundle\pibox-installer.exe C:\msys64\home\appveyor\pibox-installer-win64.exe
  - move C:\projects\pibox-installer\pibox_installer_ci_rsa C:\msys64\home\appveyor\

  - if %platform%==x86 C:\msys64\usr\bin\bash --login -c "scp -r -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa pibox-installer-win32.exe pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +'%%Y-%%m-%%d')/pibox-installer-win32.exe"
  - if %platform%==x64 C:\msys64\usr\bin\bash --login -c "scp -r -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa pibox-installer-win64.exe pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/$(date +'%%Y-%%m-%%d')/pibox-installer-win64.exe"

  - C:\msys64\usr\bin\bash --login -c "PIBOX_RELEASE=$((cd /c/projects/pibox-installer/; git tag -l --points-at HEAD) | grep -x 'v[[:digit:]]\+.[[:digit:]]\+\(.[[:digit:]]\+\)*\(-rc[[:digit:]]\+\)\?') || true; if [ $PIBOX_RELEASE ]; then mkdir -p releases/$PIBOX_RELEASE/; mv pibox-installer-win*.exe releases/$PIBOX_RELEASE/; scp -r -o StrictHostKeyChecking=no -i pibox_installer_ci_rsa releases pibox_ci@buildbot.wan.bsf-intranet.org:/srv/repos/pibox/; fi"
