---
- name: Move downloaded content to proper location
  command: mv {{ wikifundi_langpack_prefix }}{{ item }}/ {{ wikifundi_root }}/{{ item }}.africapack.kiwix.org
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: move-content

# fix path in content source code
- name: Change lua path and TMP in LocalSettings.custom.php
  replace:
    name: "{{ wikifundi_root }}/{{ item }}.africapack.kiwix.org/w/LocalSettings.custom.php"
    regexp: '^\<\?php$'
    replace: '<?php\nputenv("TMP={$wgUploadDirectory}/temp");\n$wgScribuntoEngineConf[''luastandalone''][''luaPath''] = "/usr/bin/lua5.1";'
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: move-content

# fix extensions in the content
- name: Get the Math renderer correctly
  become: yes
  shell:
    cd {{ wikifundi_root }}/{{ item }}.africapack.kiwix.org/w/extensions/Math/math;
    make clean all;
    cd {{ wikifundi_root }}/{{ item }}.africapack.kiwix.org/w/extensions/Math/texvccheck;
    make clean all;
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: move-content

- include: mark_role.yml role=wikifundi_content
  tags: move-content
