---
- name: Install catalogs
  become: yes
  become_user: "{{ username }}"
  command: ideascube catalog remotes add "{{ item.name }}" "{{ item.description }}" "{{ item.url }}"
  with_items: "{{ ansible_local.config.catalogs }}"
  tags: move-content

- name: Update ideascube catalog cache before downloading
  become: yes
  become_user: "{{ username }}"
  shell: ideascube catalog cache update
  tags: move-content

- name: Install, upgrade or remove packages
  become: yes
  become_user: "{{ username }}"
  shell: ideascube catalog install --package-cache {{ packages_cache }} --skip-sha256 {{ item.name }}
  with_items: '{{ ansible_local.config.packages | default(omit) }}'
  when: ansible_local.config.packages | length
  register: ideascube_catalog_cmd
  notify: restart kiwix
  tags: move-content

- name: Add CSS for package icon
  lineinfile:
    dest: /opt/venvs/ideascube/lib/python{{ python3_version }}/site-packages/ideascube/static/ideascube/cards.css
    line: '.card.{{ item.name|splitext|first|replace(".", "\.") }} { background-image: url("http://{{ kiwix_fqdn }}/{{ item.name }}/-/favicon"); }'
    insertafter: EOF
    state: present
  with_items: '{{ ansible_local.config.packages | default(omit) }}'
  when: ansible_local.config.packages | length
  tags: ['move-content', 'rename']

- name: Fix khanacademy icon size in CSS
  lineinfile:
    dest: /opt/venvs/ideascube/lib/python{{ python3_version }}/site-packages/ideascube/static/ideascube/cards.css
    line: '.card.khanacademy { background-size: 48px; }'
    insertafter: EOF
    state: present
  tags: move-content

- name: Add wikifundi CSS hack
  lineinfile:
    dest: /opt/venvs/ideascube/lib/python{{ python3_version }}/site-packages/ideascube/static/ideascube/cards.css
    line: '.card.tinted[href*="http://{{ item }}.{{ wikifundi_fqdn }}"], { background-image: url("http://{{ item }}.{{ wikifundi_fqdn }}/logo.png"); background-size: 80px; }'
    insertafter: EOF
    state: present
  with_items: '{{ ansible_local.config.wikifundi_languages | default(omit) }}'
  when: ansible_local.config.wikifundi_languages | length
  tags: ['move-content', 'rename']

- name: collect static for ideascube
  become: yes
  become_user: "{{ username }}"
  command: ideascube collectstatic --noinput
  notify: restart uwsgi
  tags: move-content

- set_fact:
    pkg_list: "{{ ideascube_catalog_cmd.results | map(attribute='stdout') | list }}"
  tags: move-content

- debug:
    var: pkg_list
  tags: move-content
