---
- name: Install dependencies
  apt: name={{ item }} state=latest
  with_items:
    - nginx
    - php5-fpm
    - memcached
    - nodejs
    - imagemagick
    - texlive
    - texlive-latex-extra
    - php-pear
    - php5-curl
    - php5-sqlite
    - libav-tools
    - librsvg2-bin
    - poppler-utils
    - npm
    - redis-server
    - dvipng
    - lua5.1
    - build-essential
    - ocaml
    - cjk-latex
    - texlive-fonts-recommended
    - texlive-lang-greek
    - texlive-latex-recommended
  tags: configure

- name: Link node to nodejs binary
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  tags: configure

- name: Download Parsoid
  unarchive:
    src: "{{ mirror }}/other/wikifundi/parsoid_2016-08.tar.bz2"
    dest: "{{ wikifundi_root }}"
    remote_src: True
  tags: configure

- name: Setup parsoid service
  template:
    src: parsoid.service.j2
    dest: /etc/systemd/system/parsoid.service
  tags: configure

- name: Enable and Start Parsoid
  systemd:
    name: parsoid
    state: started
    daemon_reload: yes
    enabled: yes
  tags: configure

- name: Enable and Start php-fpm
  systemd:
    name: php5-fpm
    state: started
    daemon_reload: yes
    enabled: yes
  tags: configure

- name: Copy nginx vhosts
  template:
    src: wikifundi.vhost.j2
    dest: /etc/nginx/sites-available/{{ item }}.wikifundi
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Enable nginx vhosts
  file:
    src: /etc/nginx/sites-available/{{ item }}.wikifundi
    dest: /etc/nginx/sites-enabled/{{ item }}.wikifundi
    state: link
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Move downloaded content to proper location
  command: mv {{ wikifundi_langpack_prefix }}{{ item }}/ {{ wikifundi_root }}/{{ item }}.africapack.kiwix.org
  tags: move-content

# fix path in content source code
- name: Change lua path and TMP in LocalSettings.custom.php
  replace:
    name: "{{ wikifundi_root }}/{{ item }}.africapack.kiwix.org/w/LocalSettings.custom.php"
    regexp: '^\<\?php$'
    replace: '<?php\nputenv("TMP={$wgUploadDirectory}/temp");\n$wgScribuntoEngineConf[''luastandalone''][''luaPath''] = "/usr/bin/lua5.1";'
  with_items: "{{ wikifundi_languages | default(omit) }}"
  tags: move-content

# fix extensions in the content
- name: Get the Math renderer correctly
  become: yes
  shell:
    cd {{ wikifundi_root }}/{{ item }}.africapack.kiwix.org/w/extensions/Math/math;
    make clean all;
    cd {{ wikifundi_root }}/{{ item }}.africapack.kiwix.org/w/extensions/Math/texvccheck;
    make clean all;
  with_items: "{{ wikifundi_languages | default(omit) }}"
  tags: move-content
