#!/bin/bash

echo "setting static IP on eth0"
ifconfig eth0 192.168.1.3 up

echo "adding bridge IP to the PASSLIST"
iptables -t nat -I CAPTIVE_PASSLIST 1 -s 192.168.1.1 -j ACCEPT

nbgw=$(route -n |grep -E "^0.0.0.0" | grep eth0 | wc -l)
echo "route to bridge gateway: ${nbgw}"
if [ $nbgw -eq 0 ] ; then
	echo "adding route to bridge gateway"
	route add default gw 192.168.1.1
fi

nbbgw=$(route -n |grep -E "^0.0.0.0" | grep eth1 | wc -l)
echo "route to qemu gateway: ${nbbgw}"
if [ $nbbgw -gt 0 ] ; then
	echo "removing route to qemu gateway"
	route del -net 0.0.0.0 netmask 0.0.0.0 dev eth1
fi
