---
- name: Create working directory
  file:
    path: "{{ aflatoun_root }}"
    state: directory
  tags: configure

- name: Download Aflatoun
  get_url:
    url: "{{ mirror }}/other/aflatoun/ka-lite-static-0.16.7b3.tar.gz"
    dest: /tmp/ka-lite-static-0.16.7b3.tar.gz
  tags: configure

- name: Install Aflatoun
  pip:
    name: /tmp/ka-lite-static-0.16.7b3.tar.gz
    chdir: "{{ aflatoun_root }}"
    virtualenv_command: /usr/bin/virtualenv
    virtualenv: "{{ aflatoun_env }}"
  tags: configure

- name: Create a user admin for aflatoun
  become: yes
  become_user: ideascube
  shell: KALITE_PYTHON={{ aflatoun_env }}/bin/python KALITE_HOME={{ aflatoun_root }} {{ aflatoun_env }}/bin/kalite manage setup --username={{ admin_account }} --password={{ admin_password }} --noinput --no-assessment-items
  when: admin_account is defined
  tags: configure

- name: Create a user admin for aflatoun
  become: yes
  become_user: ideascube
  shell: KALITE_PYTHON={{ aflatoun_env }}/bin/python KALITE_HOME={{ aflatoun_root }} {{ aflatoun_env }}/bin/kalite manage setup --noinput --no-assessment-items
  when: admin_account is not defined
  tags: configure

- name: Copy nginx vhost
  template:
    src: aflatoun.vhost.j2
    dest: /etc/nginx/sites-available/aflatoun
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Nginx enable Virtual host
  file:
    src: /etc/nginx/sites-available/aflatoun
    dest: /etc/nginx/sites-enabled/aflatoun
    state: link
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Setup startup file
  template:
    src: aflatoun.service.j2
    dest: /etc/systemd/system/aflatoun.service
  tags: configure

- name: Enable and Start Aflatoun
  systemd:
    name: aflatoun
    state: started
    daemon_reload: yes
    enabled: yes
  tags: configure

- include: mark_role.yml role=aflatoun_setup
  tags: configure
