---
- name: make sur wikifundi_root exists
  file:
    dest: "{{ wikifundi_root }}"
    state: directory
  tags: 
    - setup
    - reconfigure

- name: Install dependencies (tex)
  apt:
    name: "{{ item }}"
    state: latest
    autoremove: yes
    autoclean: yes
  with_items:
    - texlive
    - texlive-latex-extra
    - cjk-latex
    - texlive-fonts-recommended
    - texlive-lang-greek
    - texlive-latex-recommended
  tags: setup

- name: Install dependencies (PHP, jessie)
  apt:
    name: "{{ item }}"
    state: latest
    autoremove: yes
    autoclean: yes
  with_items:
    - php5-fpm
    - php5-curl
    - php5-sqlite
  when: ansible_distribution_release == "jessie"
  tags: setup

- name: Install dependencies (PHP, stretch)
  apt:
    name: "{{ item }}"
    state: latest
    autoremove: yes
    autoclean: yes
  with_items:
    - php-fpm
    - php-curl
    - php-sqlite3
  when: ansible_distribution_release == "stretch"
  tags: setup

- name: Install dependencies (others)
  apt:
    name: "{{ item }}"
    state: latest
    autoremove: yes
    autoclean: yes
  with_items:
    - nginx
    - memcached
    - nodejs
    - imagemagick
    - php-pear
    - libav-tools
    - librsvg2-bin
    - poppler-utils
    - npm
    - redis-server
    - dvipng
    - lua5.1
    - build-essential
    - ocaml
  tags: setup

- name: change PHP5 settings to allow file uploads up to 100MiB
  copy:
    src: 90-wikifundi.ini
    dest: /etc/php5/fpm/conf.d/90-wikifundi.ini
  when: ansible_distribution_release == "jessie"
  tags: setup

- name: change PHP7settings to allow file uploads up to 100MiB
  copy:
    src: 90-wikifundi.ini
    dest: /etc/php/7.0/fpm/conf.d/90-wikifundi.ini
  when: ansible_distribution_release == "stretch"
  tags: setup

- name: Link node to nodejs binary
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  tags: setup

- name: Setup parsoid service
  template:
    src: parsoid.service.j2
    dest: /etc/systemd/system/parsoid.service
  notify: reload systemd
  tags: setup

- name: Copy nginx vhosts
  template:
    src: wikifundi.vhost.j2
    dest: /etc/nginx/sites-available/{{ item }}.wikifundi
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['setup', 'rename']

- name: Enable nginx vhosts
  file:
    src: /etc/nginx/sites-available/{{ item }}.wikifundi
    dest: /etc/nginx/sites-enabled/{{ item }}.wikifundi
    state: link
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['setup', 'rename']
