---
- import_tasks: mediawiki.yml

- name: create wikifundi data folder
  file:
    dest: "{{ wikifundi_data_root }}"
    state: directory
  tags: ['setup', 'reconfigure']

- name: create custom config file
  template:
    src: LocalSettings.custom.php.j2
    dest: "{{ mediawiki_root }}/LocalSettings.custom.{{ item }}.php"
  with_items: "{{ ansible_local.config.wikifundi_languages | default(omit) }}"
  tags: ['reconfigure', 'rename']

- name: Add admin account to Wikifundi
  environment:
    WIKIFUNDI_LANG: "{{ item }}"
  command: php maintenance/createAndPromote.php --bureaucrat --sysop --bot --force {{ admin_account }} {{ admin_password }}
  args:
    chdir: "{{ mediawiki_root }}"
  with_items: "{{ ansible_local.config.wikifundi_languages | default(omit) }}"
  when: admin_account is defined
  tags: reconfigure

- name: Copy nginx vhosts
  template:
    src: wikifundi.vhost.j2
    dest: /etc/nginx/sites-available/{{ item }}.wikifundi
  with_items: "{{ ansible_local.config.wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['reconfigure', 'rename']
