---
- name: make sur wikifundi_root exists
  file:
    dest: "{{ wikifundi_root }}"
    state: directory
  tags: configure

- name: Install dependencies (text)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - texlive
    - texlive-latex-extra
    - cjk-latex
    - texlive-fonts-recommended
    - texlive-lang-greek
    - texlive-latex-recommended
  tags: configure

- name: Install dependencies (PHP, jessie)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php5-fpm
    - php5-curl
    - php5-sqlite
  when: ansible_distribution_release == "jessie"
  tags: configure

- name: Install dependencies (PHP, stretch)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - php-fpm
    - php-curl
    - php-sqlite3
  when: ansible_distribution_release == "stretch"
  tags: configure

- name: Install dependencies (others)
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - nginx
    - memcached
    - nodejs
    - imagemagick
    - php-pear
    - libav-tools
    - librsvg2-bin
    - poppler-utils
    - npm
    - redis-server
    - dvipng
    - lua5.1
    - build-essential
    - ocaml
  tags: configure

- name: Link node to nodejs binary
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
  tags: configure

# needs to be extracted as ideascube other otherwise tries to chmod www-data
- name: Download Parsoid
  become: yes
  become_user: ideascube
  unarchive:
    src: "{{ mirror }}/other/wikifundi/parsoid_2016-08.tar.bz2"
    dest: "{{ wikifundi_root }}"
    remote_src: True
  tags: configure

- name: Change hostnames in localsettings.js
  replace:
    name: "{{ wikifundi_root }}/parsoid/localsettings.js"
    regexp: "{{ item }}.africapack.kiwix.org"
    replace: "{{ item }}.{{ wikifundi_fqdn }}"
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: configure

- name: Setup parsoid service
  template:
    src: parsoid.service.j2
    dest: /etc/systemd/system/parsoid.service
  tags: configure

- name: Enable and Start Parsoid
  systemd:
    name: parsoid
    state: started
    daemon_reload: yes
    enabled: yes
  tags: configure

- name: Enable and Start php-fpm
  systemd:
    name: php5-fpm
    state: started
    daemon_reload: yes
    enabled: yes
  tags: configure

- name: Copy nginx vhosts
  template:
    src: wikifundi.vhost.j2
    dest: /etc/nginx/sites-available/{{ item }}.wikifundi
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['configure', 'rename']

- name: Enable nginx vhosts
  file:
    src: /etc/nginx/sites-available/{{ item }}.wikifundi
    dest: /etc/nginx/sites-enabled/{{ item }}.wikifundi
    state: link
  with_items: "{{ wikifundi_languages | default(omit) }}"
  notify: restart nginx
  tags: ['configure', 'rename']

- include: mark_role.yml role=wikifundi_setup
  tags: configure
