---
- hosts: localhost

  handlers:
    - include: handlers.yml

  pre_tasks:
    - name: Set the LED steady before upgrading !!!
      shell: echo default-on >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: ['always']

  roles:
    - role: set_custom_fact
    
      # master, resize
    - role: resize-partition
      when: ansible_local.progress.main.resize != "y"

      # master, configure (timezone, apt-update)
    - role: system
      when: ansible_local.progress.main.system != "y"

    - role: nginx
      tags: master

    - role: uwsgi
      tags: master

      # master, rename, configure
    - role: ideascube
      when: ansible_local.progress.main.ideascube != "y"

      # master, rename
    - role: kiwix
      when: ansible_local.progress.main.kiwix != "y"

      # master, rename
    - role: captive_portal
      when: captive_portal|bool and ansible_local.progress.main.captive != "y"

      # content setup (install, dependencies)
    - role: edupi
      when: edupi|bool and ansible_local.progress.main.edupi_setup != "y"

    - role: kalite_setup
      when: kalite_languages | length and ansible_local.progress.main.kalite_setup != "y"

    - role: aflatoun_setup
      when: aflatoun_languages | length and ansible_local.progress.main.aflatoun_setup != "y"

    - role: wikifundi_setup
      when: wikifundi_languages | length and ansible_local.progress.main.wikifundi_setup != "y"

      # move content
    - role: package_management
      when: packages | length and ansible_local.progress.main.packages != "y"
      tags: move-content

    - role: kalite_content
      when: kalite_languages | length and ansible_local.progress.main.kalite_content != "y"

    - role: aflatoun_content
      when: aflatoun_languages | length and ansible_local.progress.main.aflatoun_content != "y"

    - role: wikifundi_content
      when: wikifundi_languages | length and ansible_local.progress.main.wikifundi_content != "y"

      # seal the image
    - role: seal
      tags: seal

  post_tasks:
    - name: Heartbeat mode on KoomBook LED, update is over !!!
      shell: echo heartbeat >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: ['always']
