---
- hosts: localhost

  handlers:
    - name: restart systemd-logind
      service:
        name: systemd-logind
        state: restarted
      tags: ['master', 'rename']

    - name: update timezone
      command: dpkg-reconfigure --frontend noninteractive tzdata
      tags: ['master', 'configure']

    - name: Update grub
      command: update-grub
      tags: ['master']

    - name: reboot device
      command: reboot
      tags: ['master', 'hardware']

    - name: restart dnsmasq
      service:
        name: dnsmasq
        state: restarted
      tags: ['master']

    - name: restart hostapd
      service:
        name: hostapd
        state: restarted
      tags: ['master', 'rename']

    - name: restart nginx
      service:
        name: nginx
        state: restarted
      tags: ['master', 'configure', 'rename']

    - name: restart uwsgi
      service:
        name: uwsgi
        state: restarted
      tags: ['master', 'configure', 'rename']

    - name: restart edupi
      service:
        name: edupi
        state: restarted
      tags: ['master', 'configure', 'rename']

    - name: restart aflatoun
      service:
        name: aflatoun
        state: restarted
      tags: ['configure', 'move-content']

    - name: restart kalite
      service:
        name: kalite
        state: restarted
      tags: ['configure', 'move-content']

    - name: restart kiwix
      service:
        name: kiwix-server
        state: restarted
      tags: ['master', 'download-content', 'move-content']


  pre_tasks:
    - name: Set the LED steady before upgrading !!!
      shell: echo default-on >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: ['always']

  roles:
    - set_custom_fact
    
    - resize-partition

    - system
    - nginx
    - uwsgi
    - ideascube
    - kiwix

    - role: captive_portal
      when: captive_portal|bool

    - role: package_management
      when: packages | length

    - role: kalite
      when: kalite_languages | length

    - role: aflatoun
      when: aflatoun_languages | length

    - role: wikifundi
      when: wikifundi_languages | length

    - role: edupi
      when: edupi|bool

    - role: seal
      tags: seal

  post_tasks:
    - name: Heartbeat mode on KoomBook LED, update is over !!!
      shell: echo heartbeat >/sys/class/leds/a20-olinuxino-lime2:green:usr/trigger
      when: ansible_architecture == 'armv7l' and ansible_lsb.id == 'Debian'
      ignore_errors: yes
      tags: ['always']
