---
- name: Install catalogs
  become: yes
  become_user: ideascube
  command: ideascube catalog remotes add "{{ item.name }}" "{{ item.description }}" "{{ item.url }}"
  with_items: "{{ catalogs }}"
  tags: move-content

- name: Update ideascube catalog cache before downloading
  become: yes
  become_user: ideascube
  shell: ideascube catalog cache update
  tags: move-content

- name: Install, upgrade or remove packages
  become: yes
  become_user: ideascube
  shell: "{% if 'present' in item.status %}grep -m 1 -w \"{{ item.name }}\" /var/ideascube/main/catalog/installed.yml || ideascube catalog install --package-cache {{ packages_cache }} {{ item.name }}{% else %}echo '[+] nothing to do'{% endif %}"
  with_items: '{{ packages | default(omit) }}'
  when: packages | length
  register: ideascube_catalog_cmd
  notify: restart kiwix
  tags: move-content

- set_fact:
    pkg_list: "{{ ideascube_catalog_cmd.results | map(attribute='stdout') | list }}"
  tags: move-content

- debug: var=pkg_list
  tags: ['move-content']

- name: mark packages complete
  ini_file: dest=/etc/ansible/facts.d/progress.fact
    section=main
    option=packages
    value=complete
  tags: move-content
